import type { Question } from '@/types';

// ============================================================================
// TECHNICAL SUPPORT SPECIALIST
// ============================================================================

export const techSupProfessionalQuestions: Question[] = [
  {
    id: 'techsup-ts-01',
    profileId: 'technical-support',
    categoryId: 'ts-professional',
    competencyId: 'ts-troubleshooting',
    type: 'multiple-choice',
    content: {
      es: 'Un usuario reporta que su computadora se reinicia aleatoriamente. Usted ya verificó que no hay actualizaciones pendientes ni malware. ¿Cuál es el siguiente paso más adecuado en la metodología de diagnóstico?',
      en: 'A user reports their computer restarts randomly. You have already verified there are no pending updates or malware. What is the most appropriate next step in the troubleshooting methodology?',
      fr: "Un utilisateur signale que son ordinateur redémarre de manière aléatoire. Vous avez déjà vérifié qu'il n'y a pas de mises à jour en attente ni de malware. Quelle est la prochaine étape la plus appropriée dans la méthodologie de diagnostic ?",
    },
    options: [
      { id: 'a', text: { es: 'Formatear el equipo e instalar el sistema operativo de nuevo', en: 'Format the machine and reinstall the operating system', fr: "Formater la machine et réinstaller le système d'exploitation" }, value: 10 },
      { id: 'b', text: { es: 'Revisar los registros de eventos del sistema (Event Viewer) para identificar errores de hardware o controladores', en: 'Check the system event logs (Event Viewer) to identify hardware or driver errors', fr: "Vérifier les journaux d'événements système (Event Viewer) pour identifier les erreurs matérielles ou de pilotes" }, value: 100 },
      { id: 'c', text: { es: 'Cambiar la fuente de poder sin más análisis', en: 'Replace the power supply without further analysis', fr: "Remplacer l'alimentation sans autre analyse" }, value: 30 },
      { id: 'd', text: { es: 'Escalar el caso inmediatamente al nivel 3 de soporte', en: 'Immediately escalate the case to level 3 support', fr: 'Escalader immédiatement le cas au support niveau 3' }, value: 20 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 1,
    isActive: true,
  },
  {
    id: 'techsup-tm-01',
    profileId: 'technical-support',
    categoryId: 'ts-professional',
    competencyId: 'ts-ticket-management',
    type: 'scenario',
    content: {
      es: 'Es lunes por la mañana y tiene 25 tickets abiertos en la cola de soporte. Entre ellos hay: un servidor de correo caído que afecta a 200 usuarios, 10 solicitudes de reseteo de contraseña, una laptop con pantalla rota de un gerente, y 3 reportes de lentitud en la red.\n\nDescriba cómo priorizaría y organizaría estos tickets. Explique sus criterios de priorización y los tiempos de respuesta esperados.',
      en: 'It is Monday morning and you have 25 open tickets in the support queue. Among them: a downed email server affecting 200 users, 10 password reset requests, a laptop with a broken screen belonging to a manager, and 3 reports of network slowness.\n\nDescribe how you would prioritize and organize these tickets. Explain your prioritization criteria and expected response times.',
      fr: "C'est lundi matin et vous avez 25 tickets ouverts dans la file d'attente du support. Parmi eux : un serveur de messagerie en panne affectant 200 utilisateurs, 10 demandes de réinitialisation de mot de passe, un ordinateur portable avec écran cassé appartenant à un responsable, et 3 rapports de lenteur réseau.\n\nDécrivez comment vous prioriseriez et organiseriez ces tickets. Expliquez vos critères de priorisation et les temps de réponse attendus.",
    },
    rubric: {
      es: 'Evaluar: (1) Clasificación por impacto y urgencia (matriz de prioridad ITIL), (2) El servidor de correo como prioridad crítica (P1), (3) Agrupamiento de solicitudes similares (reseteos de contraseña en lote), (4) SLA awareness para cada nivel de prioridad, (5) Comunicación proactiva a usuarios afectados, (6) Documentación adecuada en cada ticket.',
      en: 'Evaluate: (1) Classification by impact and urgency (ITIL priority matrix), (2) Email server as critical priority (P1), (3) Grouping similar requests (batch password resets), (4) SLA awareness for each priority level, (5) Proactive communication to affected users, (6) Proper documentation in each ticket.',
      fr: 'Évaluer : (1) Classification par impact et urgence (matrice de priorité ITIL), (2) Serveur de messagerie comme priorité critique (P1), (3) Regroupement des demandes similaires (réinitialisations par lot), (4) Connaissance des SLA par niveau de priorité, (5) Communication proactive aux utilisateurs concernés, (6) Documentation adéquate dans chaque ticket.',
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 2,
    isActive: true,
  },
  {
    id: 'techsup-hw-01',
    profileId: 'technical-support',
    categoryId: 'ts-professional',
    competencyId: 'ts-hardware-software',
    type: 'multiple-choice',
    content: {
      es: 'Un usuario necesita que se le instale un segundo monitor en su estación de trabajo. Al conectarlo por HDMI, el monitor no muestra imagen. La computadora es un equipo de escritorio con tarjeta gráfica integrada. ¿Qué debe verificar primero?',
      en: 'A user needs a second monitor installed at their workstation. When connected via HDMI, the monitor shows no image. The computer is a desktop with integrated graphics. What should you check first?',
      fr: "Un utilisateur a besoin d'un deuxième moniteur à son poste de travail. Connecté en HDMI, le moniteur n'affiche rien. L'ordinateur est un poste de bureau avec carte graphique intégrée. Que devez-vous vérifier en premier ?",
    },
    options: [
      { id: 'a', text: { es: 'Verificar en la configuración de pantalla del sistema operativo si detecta el segundo monitor y habilitar la extensión de escritorio', en: 'Check in the OS display settings if the second monitor is detected and enable desktop extension', fr: "Vérifier dans les paramètres d'affichage du système si le deuxième moniteur est détecté et activer l'extension du bureau" }, value: 100 },
      { id: 'b', text: { es: 'Comprar una tarjeta gráfica dedicada de inmediato', en: 'Buy a dedicated graphics card immediately', fr: 'Acheter immédiatement une carte graphique dédiée' }, value: 20 },
      { id: 'c', text: { es: 'Reiniciar la computadora varias veces', en: 'Restart the computer several times', fr: "Redémarrer l'ordinateur plusieurs fois" }, value: 15 },
      { id: 'd', text: { es: 'Indicar al usuario que no es posible usar dos monitores', en: 'Tell the user it is not possible to use two monitors', fr: "Indiquer à l'utilisateur qu'il n'est pas possible d'utiliser deux moniteurs" }, value: 0 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 3,
    isActive: true,
  },
  {
    id: 'techsup-net-01',
    profileId: 'technical-support',
    categoryId: 'ts-professional',
    competencyId: 'ts-network-diagnostics',
    type: 'open-text',
    content: {
      es: 'Un departamento completo de 15 personas reporta que no pueden acceder a internet ni a los recursos compartidos de la red, pero el resto de la oficina funciona con normalidad. Describa paso a paso su proceso de diagnóstico para identificar y resolver el problema.',
      en: 'An entire department of 15 people reports they cannot access the internet or shared network resources, but the rest of the office is working normally. Describe step by step your diagnostic process to identify and resolve the problem.',
      fr: "Un département entier de 15 personnes signale qu'il ne peut accéder ni à internet ni aux ressources réseau partagées, mais le reste du bureau fonctionne normalement. Décrivez étape par étape votre processus de diagnostic pour identifier et résoudre le problème.",
    },
    rubric: {
      es: 'Evaluar: (1) Verificación de capa física (switch, cableado, patch panel del departamento), (2) Comprobación de conectividad (ping al gateway, DNS, DHCP), (3) Revisión de configuración del switch/VLAN, (4) Aislamiento del problema (hardware vs. configuración), (5) Uso de herramientas de diagnóstico (traceroute, ipconfig/ifconfig, nslookup), (6) Documentación del incidente y comunicación al departamento afectado.',
      en: 'Evaluate: (1) Physical layer verification (switch, cabling, department patch panel), (2) Connectivity checks (ping gateway, DNS, DHCP), (3) Switch/VLAN configuration review, (4) Problem isolation (hardware vs. configuration), (5) Use of diagnostic tools (traceroute, ipconfig/ifconfig, nslookup), (6) Incident documentation and communication to the affected department.',
      fr: "Évaluer : (1) Vérification couche physique (switch, câblage, panneau de brassage), (2) Vérification connectivité (ping passerelle, DNS, DHCP), (3) Révision configuration switch/VLAN, (4) Isolation du problème (matériel vs configuration), (5) Utilisation d'outils de diagnostic (traceroute, ipconfig/ifconfig, nslookup), (6) Documentation de l'incident et communication au département concerné.",
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 4,
    isActive: true,
  },
  {
    id: 'techsup-doc-01',
    profileId: 'technical-support',
    categoryId: 'ts-professional',
    competencyId: 'ts-documentation',
    type: 'scale',
    content: {
      es: '¿Qué tan familiarizado está con la creación y mantenimiento de artículos de base de conocimiento, guías de solución paso a paso y documentación técnica para usuarios finales?',
      en: 'How familiar are you with creating and maintaining knowledge base articles, step-by-step solution guides, and technical documentation for end users?',
      fr: "Dans quelle mesure êtes-vous familiarisé avec la création et la maintenance d'articles de base de connaissances, de guides de solutions pas à pas et de documentation technique pour les utilisateurs finaux ?",
    },
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: {
      min: { es: 'Nada familiarizado', en: 'Not familiar at all', fr: 'Pas du tout familiarisé' },
      max: { es: 'Muy familiarizado y lo hago regularmente', en: 'Very familiar and I do it regularly', fr: 'Très familiarisé et je le fais régulièrement' },
    },
    maxScore: 100,
    aiEvaluated: false,
    order: 5,
    isActive: true,
  },
  {
    id: 'techsup-sec-01',
    profileId: 'technical-support',
    categoryId: 'ts-professional',
    competencyId: 'ts-security-awareness',
    type: 'multiple-choice',
    content: {
      es: 'Un usuario le reenvía un correo electrónico sospechoso que recibió de un supuesto proveedor solicitando que actualice sus datos bancarios a través de un enlace. ¿Cuál es la acción correcta?',
      en: 'A user forwards you a suspicious email they received from an alleged vendor requesting they update their banking details through a link. What is the correct action?',
      fr: "Un utilisateur vous transfère un courriel suspect qu'il a reçu d'un prétendu fournisseur demandant de mettre à jour ses coordonnées bancaires via un lien. Quelle est l'action correcte ?",
    },
    options: [
      { id: 'a', text: { es: 'Abrir el enlace en un navegador seguro para verificar si es legítimo', en: 'Open the link in a secure browser to verify if it is legitimate', fr: "Ouvrir le lien dans un navigateur sécurisé pour vérifier s'il est légitime" }, value: 0 },
      { id: 'b', text: { es: 'Indicar al usuario que no haga clic, reportar al equipo de seguridad, bloquear el remitente y documentar el incidente', en: 'Tell the user not to click, report to the security team, block the sender, and document the incident', fr: "Indiquer à l'utilisateur de ne pas cliquer, signaler à l'équipe de sécurité, bloquer l'expéditeur et documenter l'incident" }, value: 100 },
      { id: 'c', text: { es: 'Eliminar el correo y decirle al usuario que no se preocupe', en: 'Delete the email and tell the user not to worry', fr: "Supprimer le courriel et dire à l'utilisateur de ne pas s'inquiéter" }, value: 20 },
      { id: 'd', text: { es: 'Reenviar el correo a todos los empleados como advertencia', en: 'Forward the email to all employees as a warning', fr: 'Transférer le courriel à tous les employés comme avertissement' }, value: 10 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 6,
    isActive: true,
  },
];

export const techSupSoftSkillsQuestions: Question[] = [
  {
    id: 'techsup-comm-01',
    profileId: 'technical-support',
    categoryId: 'ts-soft-skills',
    competencyId: 'ts-user-communication',
    type: 'scenario',
    content: {
      es: 'Una gerente de ventas, con muy poco conocimiento técnico, le llama frustrada porque no puede conectarse a la VPN para una presentación importante que tiene en 30 minutos. Ella dice: "Esto nunca funciona, siempre me pasa lo mismo y nadie me ayuda".\n\nDescriba cómo manejaría esta situación, incluyendo su comunicación verbal y los pasos técnicos.',
      en: 'A sales manager with very little technical knowledge calls you frustrated because she cannot connect to the VPN for an important presentation she has in 30 minutes. She says: "This never works, the same thing always happens and nobody helps me."\n\nDescribe how you would handle this situation, including your verbal communication and technical steps.',
      fr: "Une directrice des ventes, avec très peu de connaissances techniques, vous appelle frustrée car elle ne peut pas se connecter au VPN pour une présentation importante dans 30 minutes. Elle dit : « Ça ne marche jamais, c'est toujours la même chose et personne ne m'aide. »\n\nDécrivez comment vous géreriez cette situation, y compris votre communication verbale et les étapes techniques.",
    },
    rubric: {
      es: 'Evaluar: (1) Empatía inicial y validación de la frustración, (2) Lenguaje no técnico adaptado al nivel del usuario, (3) Transmisión de calma y seguridad, (4) Proceso de diagnóstico paso a paso guiado (credenciales, configuración VPN, conectividad), (5) Solución alternativa si no se resuelve a tiempo (hotspot, otra máquina), (6) Seguimiento posterior para prevenir recurrencia.',
      en: 'Evaluate: (1) Initial empathy and validation of frustration, (2) Non-technical language adapted to user level, (3) Conveying calmness and confidence, (4) Step-by-step guided diagnostic process (credentials, VPN config, connectivity), (5) Alternative solution if not resolved in time (hotspot, another machine), (6) Follow-up to prevent recurrence.',
      fr: "Évaluer : (1) Empathie initiale et validation de la frustration, (2) Langage non technique adapté au niveau de l'utilisateur, (3) Transmission de calme et d'assurance, (4) Processus de diagnostic guidé étape par étape (identifiants, config VPN, connectivité), (5) Solution alternative si non résolu à temps (hotspot, autre machine), (6) Suivi pour prévenir la récurrence.",
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 1,
    isActive: true,
  },
  {
    id: 'techsup-comm-02',
    profileId: 'technical-support',
    categoryId: 'ts-soft-skills',
    competencyId: 'ts-user-communication',
    type: 'multiple-choice',
    content: {
      es: 'Un usuario le pregunta: "¿Por qué mi computadora está tan lenta?". Después de diagnosticar, usted determina que el disco duro está casi lleno y la memoria RAM es insuficiente. ¿Cuál es la mejor forma de explicarle al usuario?',
      en: 'A user asks: "Why is my computer so slow?" After diagnosing, you determine the hard drive is almost full and the RAM is insufficient. What is the best way to explain to the user?',
      fr: "Un utilisateur demande : « Pourquoi mon ordinateur est-il si lent ? » Après diagnostic, vous déterminez que le disque dur est presque plein et la RAM insuffisante. Quelle est la meilleure façon d'expliquer à l'utilisateur ?",
    },
    options: [
      { id: 'a', text: { es: 'Decirle que el HDD tiene menos de 5% de espacio libre y la RAM de 4 GB es insuficiente para las aplicaciones que utiliza', en: 'Tell them the HDD has less than 5% free space and the 4 GB RAM is insufficient for the applications they use', fr: "Lui dire que le HDD a moins de 5% d'espace libre et que la RAM de 4 Go est insuffisante pour les applications utilisées" }, value: 40 },
      { id: 'b', text: { es: 'Comparar la computadora con un escritorio: "Está tan lleno de papeles que no tiene espacio para trabajar, y además necesita un escritorio más grande para abrir más documentos a la vez"', en: 'Compare the computer to a desk: "It is so full of papers there is no room to work, and it also needs a bigger desk to open more documents at once"', fr: "Comparer l'ordinateur à un bureau : « Il est tellement plein de papiers qu'il n'y a plus de place pour travailler, et il faut un bureau plus grand pour ouvrir plus de documents à la fois »" }, value: 100 },
      { id: 'c', text: { es: 'Decirle que su equipo es viejo y necesita reemplazo', en: 'Tell them their equipment is old and needs replacement', fr: 'Lui dire que son équipement est vieux et doit être remplacé' }, value: 10 },
      { id: 'd', text: { es: 'Resolver el problema sin explicar nada para no confundir al usuario', en: 'Fix the problem without explaining anything so as not to confuse the user', fr: "Résoudre le problème sans rien expliquer pour ne pas confondre l'utilisateur" }, value: 20 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 2,
    isActive: true,
  },
  {
    id: 'techsup-pat-01',
    profileId: 'technical-support',
    categoryId: 'ts-soft-skills',
    competencyId: 'ts-patience-empathy',
    type: 'multiple-choice',
    content: {
      es: 'Un usuario llama por quinta vez en la semana por el mismo problema que ya se le resolvió anteriormente. Está muy molesto y dice que "el área de sistemas no sirve para nada". ¿Cómo responde?',
      en: 'A user calls for the fifth time this week about the same issue that was previously resolved. They are very upset and say "the IT department is useless." How do you respond?',
      fr: "Un utilisateur appelle pour la cinquième fois cette semaine pour le même problème déjà résolu. Il est très mécontent et dit que « le département informatique ne sert à rien ». Comment répondez-vous ?",
    },
    options: [
      { id: 'a', text: { es: 'Decirle que el problema ya se resolvió antes y que revise las instrucciones que se le enviaron', en: 'Tell them the problem was already resolved before and to review the instructions that were sent', fr: 'Lui dire que le problème a déjà été résolu et de revoir les instructions envoyées' }, value: 15 },
      { id: 'b', text: { es: 'Escuchar con paciencia, disculparse por la inconveniencia, investigar por qué recurre el problema y ofrecer una solución definitiva o capacitación personalizada', en: 'Listen patiently, apologize for the inconvenience, investigate why the problem recurs, and offer a definitive solution or personalized training', fr: "Écouter avec patience, s'excuser pour le désagrément, enquêter sur la récurrence du problème et offrir une solution définitive ou une formation personnalisée" }, value: 100 },
      { id: 'c', text: { es: 'Transferir la llamada a un compañero para evitar el conflicto', en: 'Transfer the call to a colleague to avoid the conflict', fr: "Transférer l'appel à un collègue pour éviter le conflit" }, value: 10 },
      { id: 'd', text: { es: 'Resolver el problema rápidamente sin interactuar mucho con el usuario', en: 'Resolve the problem quickly without much user interaction', fr: "Résoudre le problème rapidement sans beaucoup d'interaction avec l'utilisateur" }, value: 30 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 3,
    isActive: true,
  },
  {
    id: 'techsup-team-01',
    profileId: 'technical-support',
    categoryId: 'ts-soft-skills',
    competencyId: 'ts-teamwork-escalation',
    type: 'scenario',
    content: {
      es: 'Lleva 45 minutos intentando resolver un problema de rendimiento en el servidor de base de datos de producción. Los usuarios del sistema de pólizas no pueden trabajar. Usted tiene conocimiento intermedio en administración de bases de datos.\n\nContexto: El DBA senior está disponible pero en otra oficina. Su supervisor directo está en una reunión con el director de operaciones.',
      en: 'You have been trying to resolve a performance issue on the production database server for 45 minutes. Users of the policy system cannot work. You have intermediate knowledge of database administration.\n\nContext: The senior DBA is available but in another office. Your direct supervisor is in a meeting with the operations director.',
      fr: "Vous essayez de résoudre un problème de performance sur le serveur de base de données de production depuis 45 minutes. Les utilisateurs du système de polices ne peuvent pas travailler. Vous avez des connaissances intermédiaires en administration de bases de données.\n\nContexte : Le DBA senior est disponible mais dans un autre bureau. Votre superviseur direct est en réunion avec le directeur des opérations.",
    },
    rubric: {
      es: 'Evaluar: (1) Reconocimiento de límites propios, (2) Escalamiento oportuno al DBA senior (no esperar más), (3) Documentación de lo que ya se intentó antes de escalar, (4) Notificación al supervisor sobre el impacto al negocio, (5) Comunicación a los usuarios afectados con tiempo estimado, (6) Colaboración efectiva con el DBA al transferir el caso.',
      en: "Evaluate: (1) Recognition of own limitations, (2) Timely escalation to senior DBA (don't wait longer), (3) Documentation of what was already tried before escalating, (4) Notification to supervisor about business impact, (5) Communication to affected users with estimated time, (6) Effective collaboration with DBA when handing off the case.",
      fr: "Évaluer : (1) Reconnaissance de ses propres limites, (2) Escalade opportune au DBA senior (ne pas attendre plus), (3) Documentation de ce qui a déjà été tenté avant d'escalader, (4) Notification au superviseur de l'impact business, (5) Communication aux utilisateurs affectés avec temps estimé, (6) Collaboration efficace avec le DBA lors du transfert du cas.",
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 4,
    isActive: true,
  },
  {
    id: 'techsup-team-02',
    profileId: 'technical-support',
    categoryId: 'ts-soft-skills',
    competencyId: 'ts-teamwork-escalation',
    type: 'scale',
    content: {
      es: '¿Qué tan cómodo se siente pidiendo ayuda o escalando un problema técnico a un compañero o nivel superior cuando reconoce que excede sus conocimientos?',
      en: 'How comfortable do you feel asking for help or escalating a technical issue to a colleague or higher level when you recognize it exceeds your knowledge?',
      fr: "À quel point vous sentez-vous à l'aise pour demander de l'aide ou escalader un problème technique à un collègue ou niveau supérieur quand vous reconnaissez que cela dépasse vos connaissances ?",
    },
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: {
      min: { es: 'Muy incómodo, prefiero resolverlo solo', en: 'Very uncomfortable, I prefer to solve it alone', fr: "Très mal à l'aise, je préfère résoudre seul" },
      max: { es: 'Totalmente cómodo, lo hago cuando es necesario', en: 'Fully comfortable, I do it when needed', fr: "Tout à fait à l'aise, je le fais quand c'est nécessaire" },
    },
    maxScore: 100,
    aiEvaluated: false,
    order: 5,
    isActive: true,
  },
];

export const techSupReadinessQuestions: Question[] = [
  {
    id: 'techsup-adapt-01',
    profileId: 'technical-support',
    categoryId: 'ts-readiness',
    competencyId: 'ts-tech-adaptability',
    type: 'multiple-choice',
    content: {
      es: 'Su empresa decide migrar de Windows a ChromeOS para el 60% de los equipos de la organización. Usted nunca ha trabajado con ChromeOS. ¿Cuál es su reacción?',
      en: "Your company decides to migrate from Windows to ChromeOS for 60% of the organization's machines. You have never worked with ChromeOS. What is your reaction?",
      fr: "Votre entreprise décide de migrer de Windows à ChromeOS pour 60% des machines de l'organisation. Vous n'avez jamais travaillé avec ChromeOS. Quelle est votre réaction ?",
    },
    options: [
      { id: 'a', text: { es: 'Expresar desacuerdo con la decisión porque Windows es más completo', en: 'Express disagreement with the decision because Windows is more complete', fr: 'Exprimer son désaccord avec la décision car Windows est plus complet' }, value: 5 },
      { id: 'b', text: { es: 'Buscar capacitación inmediata, crear un ambiente de laboratorio para practicar y preparar documentación de soporte para el equipo', en: 'Seek immediate training, set up a lab environment to practice, and prepare support documentation for the team', fr: "Chercher une formation immédiate, créer un environnement de laboratoire pour pratiquer et préparer la documentation de support pour l'équipe" }, value: 100 },
      { id: 'c', text: { es: 'Esperar a que la empresa ofrezca capacitación formal antes de hacer cualquier cosa', en: 'Wait for the company to offer formal training before doing anything', fr: "Attendre que l'entreprise offre une formation formelle avant de faire quoi que ce soit" }, value: 30 },
      { id: 'd', text: { es: 'Pedir que lo asignen a un área donde sigan usando Windows', en: 'Ask to be assigned to an area that still uses Windows', fr: "Demander à être affecté à un secteur qui continue d'utiliser Windows" }, value: 0 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 1,
    isActive: true,
  },
  {
    id: 'techsup-adapt-02',
    profileId: 'technical-support',
    categoryId: 'ts-readiness',
    competencyId: 'ts-tech-adaptability',
    type: 'scale',
    content: {
      es: '¿Qué tan dispuesto está a aprender nuevas herramientas de soporte remoto, sistemas de ticketing o plataformas en la nube por su cuenta, fuera de horario laboral si es necesario?',
      en: 'How willing are you to learn new remote support tools, ticketing systems, or cloud platforms on your own, outside of work hours if necessary?',
      fr: "Dans quelle mesure êtes-vous disposé à apprendre de nouveaux outils de support à distance, systèmes de tickets ou plateformes cloud par vous-même, en dehors des heures de travail si nécessaire ?",
    },
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: {
      min: { es: 'Nada dispuesto', en: 'Not willing at all', fr: 'Pas du tout disposé' },
      max: { es: 'Totalmente dispuesto', en: 'Fully willing', fr: 'Tout à fait disposé' },
    },
    maxScore: 100,
    aiEvaluated: false,
    order: 2,
    isActive: true,
  },
  {
    id: 'techsup-learn-01',
    profileId: 'technical-support',
    categoryId: 'ts-readiness',
    competencyId: 'ts-continuous-learning',
    type: 'open-text',
    content: {
      es: 'Describa su plan de desarrollo profesional para los próximos 12 meses en el área de soporte técnico. Incluya certificaciones que le interesen, tecnologías que quiera aprender y cómo planea mantenerse actualizado con las tendencias de la industria.',
      en: 'Describe your professional development plan for the next 12 months in the technical support area. Include certifications you are interested in, technologies you want to learn, and how you plan to stay current with industry trends.',
      fr: "Décrivez votre plan de développement professionnel pour les 12 prochains mois dans le domaine du support technique. Incluez les certifications qui vous intéressent, les technologies que vous souhaitez apprendre et comment vous prévoyez de rester à jour avec les tendances de l'industrie.",
    },
    rubric: {
      es: 'Evaluar: (1) Mención de certificaciones relevantes (CompTIA A+, ITIL, Microsoft, Google), (2) Plan concreto y realista con plazos, (3) Variedad de fuentes de aprendizaje (cursos, labs, comunidades, podcasts), (4) Alineación con tendencias actuales (cloud, IA, ciberseguridad, automatización), (5) Autoconciencia de áreas de mejora, (6) Balance entre habilidades técnicas y blandas.',
      en: 'Evaluate: (1) Mention of relevant certifications (CompTIA A+, ITIL, Microsoft, Google), (2) Concrete and realistic plan with timelines, (3) Variety of learning sources (courses, labs, communities, podcasts), (4) Alignment with current trends (cloud, AI, cybersecurity, automation), (5) Self-awareness of areas for improvement, (6) Balance between technical and soft skills.',
      fr: "Évaluer : (1) Mention de certifications pertinentes (CompTIA A+, ITIL, Microsoft, Google), (2) Plan concret et réaliste avec échéances, (3) Variété de sources d'apprentissage (cours, labs, communautés, podcasts), (4) Alignement avec les tendances actuelles (cloud, IA, cybersécurité, automatisation), (5) Conscience de ses axes d'amélioration, (6) Équilibre entre compétences techniques et interpersonnelles.",
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 3,
    isActive: true,
  },
  {
    id: 'techsup-proc-01',
    profileId: 'technical-support',
    categoryId: 'ts-readiness',
    competencyId: 'ts-process-improvement',
    type: 'scenario',
    content: {
      es: 'Después de revisar las métricas del último trimestre, usted nota que el 40% de los tickets de soporte son por reseteo de contraseña, con un tiempo promedio de resolución de 15 minutos cada uno. Esto consume aproximadamente 50 horas mensuales del equipo de soporte.\n\nProponga un plan para mejorar este proceso, considerando automatización, autoservicio y reducción de carga operativa.',
      en: "After reviewing last quarter's metrics, you notice that 40% of support tickets are for password resets, with an average resolution time of 15 minutes each. This consumes approximately 50 hours monthly of the support team's time.\n\nPropose a plan to improve this process, considering automation, self-service, and operational load reduction.",
      fr: "Après avoir examiné les métriques du dernier trimestre, vous constatez que 40% des tickets de support concernent la réinitialisation de mots de passe, avec un temps moyen de résolution de 15 minutes chacun. Cela consomme environ 50 heures mensuelles du temps de l'équipe de support.\n\nProposez un plan pour améliorer ce processus, en considérant l'automatisation, le libre-service et la réduction de la charge opérationnelle.",
    },
    rubric: {
      es: 'Evaluar: (1) Propuesta de portal de autoservicio para reseteo de contraseñas (SSPR), (2) Implementación de autenticación multifactor (MFA) para reducir bloqueos, (3) Análisis costo-beneficio de la automatización, (4) Plan de comunicación y capacitación a usuarios, (5) Métricas de éxito (reducción de tickets, tiempo ahorrado), (6) Consideraciones de seguridad en la solución propuesta.',
      en: 'Evaluate: (1) Self-service password reset portal proposal (SSPR), (2) Multi-factor authentication (MFA) implementation to reduce lockouts, (3) Cost-benefit analysis of automation, (4) User communication and training plan, (5) Success metrics (ticket reduction, time saved), (6) Security considerations in the proposed solution.',
      fr: "Évaluer : (1) Proposition de portail libre-service de réinitialisation (SSPR), (2) Implémentation de l'authentification multifacteur (MFA) pour réduire les blocages, (3) Analyse coût-bénéfice de l'automatisation, (4) Plan de communication et formation des utilisateurs, (5) Métriques de succès (réduction des tickets, temps économisé), (6) Considérations de sécurité dans la solution proposée.",
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 4,
    isActive: true,
  },
  {
    id: 'techsup-proc-02',
    profileId: 'technical-support',
    categoryId: 'ts-readiness',
    competencyId: 'ts-process-improvement',
    type: 'multiple-choice',
    content: {
      es: '¿Cuál es el enfoque más efectivo para mejorar continuamente los procesos de un equipo de soporte técnico?',
      en: 'What is the most effective approach to continuously improve technical support team processes?',
      fr: "Quelle est l'approche la plus efficace pour améliorer continuellement les processus d'une équipe de support technique ?",
    },
    options: [
      { id: 'a', text: { es: 'Esperar a que los usuarios se quejen para identificar los problemas', en: 'Wait for users to complain to identify problems', fr: 'Attendre que les utilisateurs se plaignent pour identifier les problèmes' }, value: 5 },
      { id: 'b', text: { es: 'Analizar métricas regularmente (MTTR, FCR, CSAT), identificar tendencias, implementar mejoras y medir resultados', en: 'Regularly analyze metrics (MTTR, FCR, CSAT), identify trends, implement improvements, and measure results', fr: 'Analyser régulièrement les métriques (MTTR, FCR, CSAT), identifier les tendances, implémenter des améliorations et mesurer les résultats' }, value: 100 },
      { id: 'c', text: { es: 'Contratar más personal cuando la carga de trabajo aumente', en: 'Hire more staff when the workload increases', fr: 'Embaucher plus de personnel quand la charge de travail augmente' }, value: 20 },
      { id: 'd', text: { es: 'Copiar las prácticas de otras empresas del sector', en: 'Copy practices from other companies in the sector', fr: "Copier les pratiques d'autres entreprises du secteur" }, value: 25 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 5,
    isActive: true,
  },
];
