import type { Question } from '@/types';

// ============================================================================
// ACCOUNTING MANAGER QUESTIONS
// ============================================================================

// --- Professional Skills (6 questions) ---
export const acctMgrProfessionalQuestions: Question[] = [
  {
    id: 'am-fr-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-professional',
    competencyId: 'acctmgr-financial-reporting',
    type: 'multiple-choice',
    content: {
      es: 'Al preparar los estados financieros de cierre anual, usted detecta que una subsidiaria ha registrado ingresos por un contrato cuya entrega de servicios no se ha completado. Según NIIF 15, ¿cuál es la acción correcta?',
      en: 'While preparing year-end financial statements, you discover that a subsidiary has recorded revenue for a contract whose service delivery has not been completed. Under IFRS 15, what is the correct action?',
      fr: 'Lors de la préparation des états financiers de clôture annuelle, vous découvrez qu\'une filiale a comptabilisé des revenus pour un contrat dont la prestation de services n\'est pas terminée. Selon IFRS 15, quelle est l\'action correcte ?',
    },
    options: [
      { id: 'a', text: { es: 'Mantener el registro tal como está, ya que el contrato fue firmado', en: 'Keep the record as is, since the contract was signed', fr: 'Maintenir l\'enregistrement tel quel, puisque le contrat a été signé' }, value: 0 },
      { id: 'b', text: { es: 'Reversar el ingreso y reconocerlo como pasivo por contrato (ingreso diferido) hasta que se cumplan las obligaciones de desempeño', en: 'Reverse the revenue and recognize it as a contract liability (deferred revenue) until performance obligations are satisfied', fr: 'Contre-passer le revenu et le comptabiliser en passif contractuel (produit différé) jusqu\'à ce que les obligations de performance soient satisfaites' }, value: 100 },
      { id: 'c', text: { es: 'Registrar solo el 50% del ingreso como estimación', en: 'Record only 50% of the revenue as an estimate', fr: 'Comptabiliser seulement 50 % du revenu comme estimation' }, value: 20 },
      { id: 'd', text: { es: 'Reportar el ingreso completo y hacer una nota de revelación', en: 'Report the full revenue and add a disclosure note', fr: 'Déclarer le revenu complet et ajouter une note d\'information' }, value: 30 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 1,
    isActive: true,
  },
  {
    id: 'am-tc-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-professional',
    competencyId: 'acctmgr-tax-compliance',
    type: 'scenario',
    content: {
      es: 'La autoridad tributaria de su país acaba de publicar una reforma fiscal que cambia significativamente el tratamiento del IVA en servicios digitales, con vigencia en 60 días. Su empresa presta servicios digitales a clientes en tres países de la región.\n\nContexto: Usted es el Gerente de Contabilidad y debe coordinar la adaptación de la empresa a esta nueva normativa.',
      en: 'The tax authority in your country has just published a tax reform that significantly changes the VAT treatment of digital services, effective in 60 days. Your company provides digital services to clients in three countries in the region.\n\nContext: You are the Accounting Manager and must coordinate the company\'s adaptation to this new regulation.',
      fr: 'L\'autorité fiscale de votre pays vient de publier une réforme fiscale qui modifie considérablement le traitement de la TVA sur les services numériques, avec effet dans 60 jours. Votre entreprise fournit des services numériques à des clients dans trois pays de la région.\n\nContexte : Vous êtes le Responsable Comptable et devez coordonner l\'adaptation de l\'entreprise à cette nouvelle réglementation.',
    },
    rubric: {
      es: 'Evaluar: (1) Plan de acción con cronograma para implementar antes de la fecha límite, (2) Identificación de impacto en facturación, registros contables y flujo de caja, (3) Coordinación con asesores legales/tributarios externos, (4) Actualización de parametrización del ERP, (5) Capacitación al equipo contable y de facturación, (6) Comunicación a clientes sobre cambios en facturación.',
      en: 'Evaluate: (1) Action plan with timeline to implement before the deadline, (2) Identification of impact on invoicing, accounting records, and cash flow, (3) Coordination with external legal/tax advisors, (4) Update of ERP parameterization, (5) Training for accounting and billing teams, (6) Communication to clients about invoicing changes.',
      fr: 'Évaluer : (1) Plan d\'action avec calendrier pour mise en œuvre avant la date limite, (2) Identification de l\'impact sur la facturation, les écritures comptables et la trésorerie, (3) Coordination avec les conseillers juridiques/fiscaux externes, (4) Mise à jour du paramétrage de l\'ERP, (5) Formation de l\'équipe comptable et de facturation, (6) Communication aux clients sur les changements de facturation.',
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 2,
    isActive: true,
  },
  {
    id: 'am-ic-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-professional',
    competencyId: 'acctmgr-internal-controls',
    type: 'multiple-choice',
    content: {
      es: 'Durante una revisión de controles internos, usted descubre que el mismo empleado que aprueba órdenes de compra también autoriza los pagos a proveedores. ¿Cuál es el principal riesgo y la acción correcta?',
      en: 'During an internal controls review, you discover that the same employee who approves purchase orders also authorizes payments to vendors. What is the main risk and the correct action?',
      fr: 'Lors d\'une revue des contrôles internes, vous découvrez que le même employé qui approuve les bons de commande autorise également les paiements aux fournisseurs. Quel est le risque principal et l\'action correcte ?',
    },
    options: [
      { id: 'a', text: { es: 'No hay riesgo significativo si el empleado es de confianza', en: 'There is no significant risk if the employee is trustworthy', fr: 'Il n\'y a pas de risque significatif si l\'employé est digne de confiance' }, value: 0 },
      { id: 'b', text: { es: 'Existe riesgo de fraude por falta de segregación de funciones; se debe separar las funciones de aprobación y pago entre personas distintas inmediatamente', en: 'There is a fraud risk due to lack of segregation of duties; the approval and payment functions must be separated between different people immediately', fr: 'Il existe un risque de fraude dû au manque de séparation des fonctions ; les fonctions d\'approbation et de paiement doivent être séparées entre différentes personnes immédiatement' }, value: 100 },
      { id: 'c', text: { es: 'Basta con que un supervisor revise los pagos mensualmente', en: 'It is enough for a supervisor to review payments monthly', fr: 'Il suffit qu\'un superviseur vérifie les paiements mensuellement' }, value: 30 },
      { id: 'd', text: { es: 'Se debe documentar la situación pero no es urgente cambiarla', en: 'The situation should be documented but it is not urgent to change it', fr: 'La situation doit être documentée mais il n\'est pas urgent de la changer' }, value: 15 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 3,
    isActive: true,
  },
  {
    id: 'am-bg-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-professional',
    competencyId: 'acctmgr-budgeting',
    type: 'open-text',
    content: {
      es: 'Describa su proceso para elaborar el presupuesto anual de una empresa. Incluya cómo recopila información de las diferentes áreas, qué herramientas utiliza, cómo maneja las variaciones entre lo presupuestado y lo real, y cómo presenta los resultados a la alta dirección.',
      en: 'Describe your process for preparing a company\'s annual budget. Include how you gather information from different departments, what tools you use, how you handle variances between budgeted and actual figures, and how you present results to senior management.',
      fr: 'Décrivez votre processus d\'élaboration du budget annuel d\'une entreprise. Incluez comment vous collectez les informations des différents départements, quels outils vous utilisez, comment vous gérez les écarts entre le budgété et le réel, et comment vous présentez les résultats à la direction.',
    },
    rubric: {
      es: 'Evaluar: (1) Metodología estructurada de planificación presupuestaria (bottom-up, top-down o combinada), (2) Herramientas y sistemas utilizados (ERP, hojas de cálculo, BI), (3) Proceso de recopilación de datos de áreas operativas, (4) Análisis de variaciones con acciones correctivas, (5) Capacidad de comunicación con lenguaje claro para la alta dirección.',
      en: 'Evaluate: (1) Structured budget planning methodology (bottom-up, top-down, or combined), (2) Tools and systems used (ERP, spreadsheets, BI), (3) Process for gathering data from operational areas, (4) Variance analysis with corrective actions, (5) Communication ability with clear language for senior management.',
      fr: 'Évaluer : (1) Méthodologie structurée de planification budgétaire (ascendante, descendante ou combinée), (2) Outils et systèmes utilisés (ERP, tableurs, BI), (3) Processus de collecte de données des domaines opérationnels, (4) Analyse des écarts avec actions correctives, (5) Capacité de communication avec un langage clair pour la direction.',
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 4,
    isActive: true,
  },
  {
    id: 'am-erp-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-professional',
    competencyId: 'acctmgr-erp-management',
    type: 'scale',
    content: {
      es: '¿Qué tan competente se considera en la administración de sistemas ERP contables (SAP, Oracle, NetSuite, Dynamics u otros), incluyendo configuración de módulos financieros, generación de reportes y resolución de problemas técnicos?',
      en: 'How competent do you consider yourself in managing accounting ERP systems (SAP, Oracle, NetSuite, Dynamics, or others), including configuring financial modules, generating reports, and troubleshooting technical issues?',
      fr: 'À quel point vous considérez-vous compétent dans la gestion des systèmes ERP comptables (SAP, Oracle, NetSuite, Dynamics ou autres), y compris la configuration des modules financiers, la génération de rapports et la résolution de problèmes techniques ?',
    },
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: {
      min: { es: 'Conocimiento básico', en: 'Basic knowledge', fr: 'Connaissance de base' },
      max: { es: 'Dominio avanzado', en: 'Advanced mastery', fr: 'Maîtrise avancée' },
    },
    maxScore: 100,
    aiEvaluated: false,
    order: 5,
    isActive: true,
  },
  {
    id: 'am-fr-02',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-professional',
    competencyId: 'acctmgr-financial-reporting',
    type: 'multiple-choice',
    content: {
      es: 'Durante el cierre mensual, el equipo de cuentas por cobrar le informa que un cliente importante con una factura de $500,000 ha entrado en proceso de insolvencia. ¿Cuál es el tratamiento contable adecuado según NIIF 9?',
      en: 'During the monthly close, the accounts receivable team informs you that a major client with a $500,000 invoice has entered insolvency proceedings. What is the appropriate accounting treatment under IFRS 9?',
      fr: 'Lors de la clôture mensuelle, l\'équipe des comptes clients vous informe qu\'un client important avec une facture de 500 000 $ est entré en procédure d\'insolvabilité. Quel est le traitement comptable approprié selon IFRS 9 ?',
    },
    options: [
      { id: 'a', text: { es: 'Esperar 90 días para ver si el cliente paga antes de tomar acción', en: 'Wait 90 days to see if the client pays before taking action', fr: 'Attendre 90 jours pour voir si le client paie avant d\'agir' }, value: 10 },
      { id: 'b', text: { es: 'Evaluar la pérdida crediticia esperada, constituir una provisión basada en la probabilidad de recuperación y revelar en notas a los estados financieros', en: 'Assess the expected credit loss, set up a provision based on recovery probability, and disclose in notes to the financial statements', fr: 'Évaluer la perte de crédit attendue, constituer une provision basée sur la probabilité de recouvrement et communiquer dans les notes aux états financiers' }, value: 100 },
      { id: 'c', text: { es: 'Dar de baja inmediatamente la cuenta por cobrar contra resultados', en: 'Immediately write off the receivable against income', fr: 'Passer immédiatement la créance en perte contre le résultat' }, value: 30 },
      { id: 'd', text: { es: 'Reclasificar como cuenta de largo plazo y no provisionar', en: 'Reclassify as a long-term receivable and do not provision', fr: 'Reclasser en créance à long terme et ne pas provisionner' }, value: 5 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 6,
    isActive: true,
  },
];

// --- Soft Skills (5 questions) ---
export const acctMgrSoftSkillsQuestions: Question[] = [
  {
    id: 'am-ld-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-soft-skills',
    competencyId: 'acctmgr-leadership',
    type: 'scenario',
    content: {
      es: 'Dos miembros clave de su equipo contable han tenido un conflicto serio sobre la metodología de registro de provisiones. El desacuerdo está afectando los tiempos de cierre mensual y el ambiente de trabajo. Uno de ellos amenaza con renunciar si no se le da la razón.\n\nContexto: Ambos son empleados con más de 5 años de antigüedad, alto rendimiento, y el cierre mensual es en 3 días.',
      en: 'Two key members of your accounting team have had a serious conflict over the methodology for recording provisions. The disagreement is affecting monthly close timelines and the work environment. One of them threatens to resign if not proven right.\n\nContext: Both are employees with over 5 years of tenure, high performance, and the monthly close is in 3 days.',
      fr: 'Deux membres clés de votre équipe comptable ont eu un conflit sérieux sur la méthodologie de comptabilisation des provisions. Le désaccord affecte les délais de clôture mensuelle et l\'ambiance de travail. L\'un d\'eux menace de démissionner si on ne lui donne pas raison.\n\nContexte : Les deux sont des employés avec plus de 5 ans d\'ancienneté, de haute performance, et la clôture mensuelle est dans 3 jours.',
    },
    rubric: {
      es: 'Evaluar: (1) Capacidad de mediación y escucha activa de ambas partes, (2) Separación del problema técnico del conflicto personal, (3) Decisión basada en normativa contable (no en preferencias personales), (4) Plan para asegurar el cierre a tiempo, (5) Seguimiento posterior para prevenir recurrencia, (6) Manejo profesional de la amenaza de renuncia.',
      en: 'Evaluate: (1) Mediation ability and active listening to both parties, (2) Separation of the technical issue from the personal conflict, (3) Decision based on accounting standards (not personal preferences), (4) Plan to ensure timely close, (5) Follow-up to prevent recurrence, (6) Professional handling of the resignation threat.',
      fr: 'Évaluer : (1) Capacité de médiation et écoute active des deux parties, (2) Séparation du problème technique du conflit personnel, (3) Décision basée sur les normes comptables (pas les préférences personnelles), (4) Plan pour assurer la clôture à temps, (5) Suivi pour prévenir la récurrence, (6) Gestion professionnelle de la menace de démission.',
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 1,
    isActive: true,
  },
  {
    id: 'am-cm-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-soft-skills',
    competencyId: 'acctmgr-communication',
    type: 'open-text',
    content: {
      es: 'El director general le solicita que presente los resultados financieros del trimestre ante el consejo de administración, donde la mayoría de los miembros no tienen formación contable. ¿Cómo estructura su presentación para que sea comprensible, relevante y útil para la toma de decisiones?',
      en: 'The CEO asks you to present the quarterly financial results to the board of directors, where most members do not have an accounting background. How do you structure your presentation to be understandable, relevant, and useful for decision-making?',
      fr: 'Le directeur général vous demande de présenter les résultats financiers du trimestre au conseil d\'administration, dont la plupart des membres n\'ont pas de formation comptable. Comment structurez-vous votre présentation pour qu\'elle soit compréhensible, pertinente et utile à la prise de décision ?',
    },
    rubric: {
      es: 'Evaluar: (1) Uso de visualizaciones y gráficos en lugar de tablas complejas, (2) Enfoque en indicadores clave (KPIs) relevantes para la estrategia, (3) Comparación con períodos anteriores y presupuesto, (4) Lenguaje accesible sin jerga técnica excesiva, (5) Inclusión de recomendaciones accionables basadas en los datos.',
      en: 'Evaluate: (1) Use of visualizations and charts instead of complex tables, (2) Focus on key performance indicators (KPIs) relevant to strategy, (3) Comparison with prior periods and budget, (4) Accessible language without excessive technical jargon, (5) Inclusion of actionable recommendations based on data.',
      fr: 'Évaluer : (1) Utilisation de visualisations et graphiques au lieu de tableaux complexes, (2) Accent sur les indicateurs clés de performance (KPI) pertinents pour la stratégie, (3) Comparaison avec les périodes précédentes et le budget, (4) Langage accessible sans jargon technique excessif, (5) Inclusion de recommandations actionnables basées sur les données.',
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 2,
    isActive: true,
  },
  {
    id: 'am-ps-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-soft-skills',
    competencyId: 'acctmgr-problem-solving',
    type: 'multiple-choice',
    content: {
      es: 'Al conciliar las cuentas bancarias del cierre mensual, encuentra una diferencia de $45,000 que no puede identificar de inmediato. El plazo de cierre es mañana. ¿Cuál es su enfoque?',
      en: 'While reconciling bank accounts for the monthly close, you find a $45,000 difference that you cannot immediately identify. The close deadline is tomorrow. What is your approach?',
      fr: 'Lors du rapprochement des comptes bancaires pour la clôture mensuelle, vous trouvez une différence de 45 000 $ que vous ne pouvez pas identifier immédiatement. La date limite de clôture est demain. Quelle est votre approche ?',
    },
    options: [
      { id: 'a', text: { es: 'Registrar un ajuste contable genérico para cuadrar y revisarlo después del cierre', en: 'Record a generic accounting adjustment to balance and review it after close', fr: 'Enregistrer un ajustement comptable générique pour équilibrer et le vérifier après la clôture' }, value: 10 },
      { id: 'b', text: { es: 'Segmentar la diferencia por rango de fechas, cruzar con el diario de transacciones, verificar partidas en tránsito y, si persiste, documentar el análisis parcial e informar al CFO antes de cerrar', en: 'Segment the difference by date range, cross-reference with the transaction journal, verify items in transit, and if it persists, document the partial analysis and inform the CFO before closing', fr: 'Segmenter la différence par plage de dates, croiser avec le journal des transactions, vérifier les éléments en transit et, si elle persiste, documenter l\'analyse partielle et informer le CFO avant la clôture' }, value: 100 },
      { id: 'c', text: { es: 'Pedir una extensión del plazo de cierre hasta encontrar la diferencia', en: 'Request a deadline extension until the difference is found', fr: 'Demander une extension du délai jusqu\'à ce que la différence soit trouvée' }, value: 40 },
      { id: 'd', text: { es: 'Asumir que es un error del banco y esperar el siguiente estado de cuenta', en: 'Assume it is a bank error and wait for the next statement', fr: 'Supposer que c\'est une erreur de la banque et attendre le prochain relevé' }, value: 5 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 3,
    isActive: true,
  },
  {
    id: 'am-ld-02',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-soft-skills',
    competencyId: 'acctmgr-leadership',
    type: 'scale',
    content: {
      es: '¿Con qué frecuencia realiza reuniones individuales con los miembros de su equipo para dar retroalimentación sobre su desempeño, discutir su desarrollo profesional y alinear prioridades?',
      en: 'How frequently do you hold one-on-one meetings with your team members to provide performance feedback, discuss their professional development, and align priorities?',
      fr: 'À quelle fréquence tenez-vous des réunions individuelles avec les membres de votre équipe pour donner un retour sur leur performance, discuter de leur développement professionnel et aligner les priorités ?',
    },
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: {
      min: { es: 'Nunca o casi nunca', en: 'Never or almost never', fr: 'Jamais ou presque jamais' },
      max: { es: 'Semanalmente de forma estructurada', en: 'Weekly in a structured manner', fr: 'Hebdomadairement de manière structurée' },
    },
    maxScore: 100,
    aiEvaluated: false,
    order: 4,
    isActive: true,
  },
  {
    id: 'am-cm-02',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-soft-skills',
    competencyId: 'acctmgr-communication',
    type: 'multiple-choice',
    content: {
      es: 'El gerente de ventas le solicita un reporte urgente sobre la rentabilidad por línea de producto. Usted sabe que los datos de costos indirectos no están completamente asignados. ¿Cómo responde?',
      en: 'The sales manager requests an urgent report on profitability by product line. You know that indirect cost data is not fully allocated. How do you respond?',
      fr: 'Le directeur des ventes vous demande un rapport urgent sur la rentabilité par ligne de produit. Vous savez que les données de coûts indirects ne sont pas entièrement réparties. Comment répondez-vous ?',
    },
    options: [
      { id: 'a', text: { es: 'Enviar el reporte solo con costos directos sin ninguna explicación', en: 'Send the report with only direct costs without any explanation', fr: 'Envoyer le rapport avec uniquement les coûts directs sans aucune explication' }, value: 10 },
      { id: 'b', text: { es: 'Entregar el reporte con los datos disponibles, señalar claramente las limitaciones de la información e incluir supuestos de asignación de costos indirectos con una nota sobre el margen de error', en: 'Deliver the report with available data, clearly note the information limitations, and include indirect cost allocation assumptions with a note about the margin of error', fr: 'Fournir le rapport avec les données disponibles, indiquer clairement les limitations de l\'information et inclure des hypothèses d\'allocation des coûts indirects avec une note sur la marge d\'erreur' }, value: 100 },
      { id: 'c', text: { es: 'Negarse a entregar el reporte hasta que los datos estén completos', en: 'Refuse to deliver the report until the data is complete', fr: 'Refuser de fournir le rapport jusqu\'à ce que les données soient complètes' }, value: 25 },
      { id: 'd', text: { es: 'Estimar los costos indirectos de forma aproximada y presentar las cifras como definitivas', en: 'Roughly estimate indirect costs and present the figures as final', fr: 'Estimer approximativement les coûts indirects et présenter les chiffres comme définitifs' }, value: 15 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 5,
    isActive: true,
  },
];

// --- Readiness for Change (5 questions) ---
export const acctMgrReadinessQuestions: Question[] = [
  {
    id: 'am-ra-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-readiness',
    competencyId: 'acctmgr-regulatory-adaptability',
    type: 'scenario',
    content: {
      es: 'Su país ha decidido adoptar plenamente las NIIF S1 y S2 (estándares de sostenibilidad) a partir del próximo año fiscal. Su empresa nunca ha preparado reportes de sostenibilidad y la junta directiva espera que el departamento de contabilidad lidere esta transición.\n\nContexto: No cuenta con personal especializado en reportes ESG y el presupuesto para nuevas contrataciones es limitado.',
      en: 'Your country has decided to fully adopt IFRS S1 and S2 (sustainability standards) starting next fiscal year. Your company has never prepared sustainability reports and the board expects the accounting department to lead this transition.\n\nContext: You have no staff specialized in ESG reporting and the budget for new hires is limited.',
      fr: 'Votre pays a décidé d\'adopter pleinement les normes IFRS S1 et S2 (normes de durabilité) à partir du prochain exercice fiscal. Votre entreprise n\'a jamais préparé de rapports de durabilité et le conseil d\'administration attend que le département comptable dirige cette transition.\n\nContexte : Vous n\'avez pas de personnel spécialisé dans les rapports ESG et le budget pour de nouvelles embauches est limité.',
    },
    rubric: {
      es: 'Evaluar: (1) Análisis de brechas entre la situación actual y los requerimientos de NIIF S1/S2, (2) Plan de capacitación del equipo existente, (3) Propuesta de alianzas con consultores externos o intercambio con otras empresas, (4) Diseño de un plan de implementación por fases, (5) Identificación de datos necesarios y áreas responsables de proveerlos, (6) Gestión proactiva de expectativas con la junta directiva.',
      en: 'Evaluate: (1) Gap analysis between current situation and IFRS S1/S2 requirements, (2) Training plan for existing team, (3) Proposal for partnerships with external consultants or knowledge exchange with other companies, (4) Design of a phased implementation plan, (5) Identification of required data and areas responsible for providing it, (6) Proactive management of board expectations.',
      fr: 'Évaluer : (1) Analyse des écarts entre la situation actuelle et les exigences IFRS S1/S2, (2) Plan de formation de l\'équipe existante, (3) Proposition de partenariats avec des consultants externes ou échange avec d\'autres entreprises, (4) Conception d\'un plan de mise en œuvre par phases, (5) Identification des données nécessaires et des domaines responsables de les fournir, (6) Gestion proactive des attentes du conseil d\'administration.',
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 1,
    isActive: true,
  },
  {
    id: 'am-dt-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-readiness',
    competencyId: 'acctmgr-digital-transformation',
    type: 'multiple-choice',
    content: {
      es: 'La dirección le propone implementar una herramienta de inteligencia artificial para automatizar la conciliación bancaria y la clasificación de asientos contables. Algunos miembros de su equipo se sienten amenazados. ¿Cuál es su enfoque?',
      en: 'Management proposes implementing an AI tool to automate bank reconciliation and journal entry classification. Some of your team members feel threatened. What is your approach?',
      fr: 'La direction vous propose d\'implémenter un outil d\'intelligence artificielle pour automatiser le rapprochement bancaire et la classification des écritures comptables. Certains membres de votre équipe se sentent menacés. Quelle est votre approche ?',
    },
    options: [
      { id: 'a', text: { es: 'Implementar la herramienta sin consultar al equipo para evitar resistencia', en: 'Implement the tool without consulting the team to avoid resistance', fr: 'Implémenter l\'outil sans consulter l\'équipe pour éviter la résistance' }, value: 5 },
      { id: 'b', text: { es: 'Involucrar al equipo en la evaluación y prueba piloto, explicar cómo la IA liberará tiempo para análisis de mayor valor, y diseñar un plan de capacitación para desarrollar nuevas competencias', en: 'Involve the team in evaluation and pilot testing, explain how AI will free time for higher-value analysis, and design a training plan to develop new competencies', fr: 'Impliquer l\'équipe dans l\'évaluation et le test pilote, expliquer comment l\'IA libérera du temps pour des analyses à plus forte valeur ajoutée, et concevoir un plan de formation pour développer de nouvelles compétences' }, value: 100 },
      { id: 'c', text: { es: 'Rechazar la propuesta porque la IA podría generar errores contables', en: 'Reject the proposal because AI could generate accounting errors', fr: 'Rejeter la proposition car l\'IA pourrait générer des erreurs comptables' }, value: 10 },
      { id: 'd', text: { es: 'Aceptar pero asignar la herramienta solo a los miembros más jóvenes del equipo', en: 'Accept but assign the tool only to the youngest team members', fr: 'Accepter mais assigner l\'outil uniquement aux membres les plus jeunes de l\'équipe' }, value: 25 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 2,
    isActive: true,
  },
  {
    id: 'am-ci-01',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-readiness',
    competencyId: 'acctmgr-continuous-improvement',
    type: 'open-text',
    content: {
      es: 'El proceso de cierre mensual de su departamento toma actualmente 12 días hábiles. La dirección le pide reducirlo a 5 días en un plazo de 6 meses. Describa su estrategia para lograrlo, incluyendo las acciones específicas, los cambios de proceso y las herramientas que implementaría.',
      en: 'Your department\'s monthly close process currently takes 12 business days. Management asks you to reduce it to 5 days within 6 months. Describe your strategy to achieve this, including specific actions, process changes, and tools you would implement.',
      fr: 'Le processus de clôture mensuelle de votre département prend actuellement 12 jours ouvrables. La direction vous demande de le réduire à 5 jours dans un délai de 6 mois. Décrivez votre stratégie pour y parvenir, y compris les actions spécifiques, les changements de processus et les outils que vous mettriez en œuvre.',
    },
    rubric: {
      es: 'Evaluar: (1) Mapeo del proceso actual e identificación de cuellos de botella, (2) Automatización de tareas repetitivas (conciliaciones, asientos recurrentes), (3) Implementación de cierres parciales (soft close) durante el mes, (4) Redefinición de roles y responsabilidades con cronograma detallado, (5) Métricas de seguimiento y plan de mejora iterativo, (6) Capacitación del equipo en nuevos procesos.',
      en: 'Evaluate: (1) Mapping current process and identifying bottlenecks, (2) Automating repetitive tasks (reconciliations, recurring entries), (3) Implementing partial closes (soft close) during the month, (4) Redefining roles and responsibilities with a detailed timeline, (5) Tracking metrics and iterative improvement plan, (6) Training the team on new processes.',
      fr: 'Évaluer : (1) Cartographie du processus actuel et identification des goulots d\'étranglement, (2) Automatisation des tâches répétitives (rapprochements, écritures récurrentes), (3) Mise en place de clôtures partielles (soft close) pendant le mois, (4) Redéfinition des rôles et responsabilités avec un calendrier détaillé, (5) Métriques de suivi et plan d\'amélioration itératif, (6) Formation de l\'équipe aux nouveaux processus.',
    },
    maxScore: 100,
    aiEvaluated: true,
    order: 3,
    isActive: true,
  },
  {
    id: 'am-dt-02',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-readiness',
    competencyId: 'acctmgr-digital-transformation',
    type: 'scale',
    content: {
      es: '¿Qué tan abierto está a adoptar nuevas tecnologías contables como RPA (automatización robótica de procesos), herramientas de analítica avanzada y plataformas de contabilidad en la nube para reemplazar procesos manuales tradicionales?',
      en: 'How open are you to adopting new accounting technologies such as RPA (robotic process automation), advanced analytics tools, and cloud accounting platforms to replace traditional manual processes?',
      fr: 'À quel point êtes-vous ouvert à l\'adoption de nouvelles technologies comptables telles que la RPA (automatisation robotique des processus), les outils d\'analytique avancée et les plateformes de comptabilité cloud pour remplacer les processus manuels traditionnels ?',
    },
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: {
      min: { es: 'Prefiero los procesos tradicionales', en: 'I prefer traditional processes', fr: 'Je préfère les processus traditionnels' },
      max: { es: 'Busco activamente nuevas tecnologías para implementar', en: 'I actively seek new technologies to implement', fr: 'Je recherche activement de nouvelles technologies à implémenter' },
    },
    maxScore: 100,
    aiEvaluated: false,
    order: 4,
    isActive: true,
  },
  {
    id: 'am-ra-02',
    profileId: 'accounting-manager',
    categoryId: 'acctmgr-readiness',
    competencyId: 'acctmgr-regulatory-adaptability',
    type: 'multiple-choice',
    content: {
      es: 'Se anuncia que la facturación electrónica será obligatoria en su país en 90 días, con un formato XML específico que requiere integración con el sistema tributario nacional. Su ERP actual no soporta este formato. ¿Qué hace primero?',
      en: 'It is announced that electronic invoicing will be mandatory in your country in 90 days, with a specific XML format requiring integration with the national tax system. Your current ERP does not support this format. What do you do first?',
      fr: 'On annonce que la facturation électronique sera obligatoire dans votre pays dans 90 jours, avec un format XML spécifique nécessitant une intégration avec le système fiscal national. Votre ERP actuel ne supporte pas ce format. Que faites-vous en premier ?',
    },
    options: [
      { id: 'a', text: { es: 'Esperar a que el proveedor del ERP lance una actualización', en: 'Wait for the ERP vendor to release an update', fr: 'Attendre que le fournisseur de l\'ERP publie une mise à jour' }, value: 15 },
      { id: 'b', text: { es: 'Evaluar rápidamente las opciones: módulo adicional del ERP, proveedor de facturación electrónica tercerizado o desarrollo interno, y presentar un análisis costo-beneficio a la dirección con un cronograma de implementación', en: 'Quickly evaluate options: additional ERP module, third-party e-invoicing provider, or internal development, and present a cost-benefit analysis to management with an implementation timeline', fr: 'Évaluer rapidement les options : module ERP supplémentaire, fournisseur tiers de facturation électronique ou développement interne, et présenter une analyse coût-bénéfice à la direction avec un calendrier de mise en œuvre' }, value: 100 },
      { id: 'c', text: { es: 'Contratar inmediatamente un proveedor externo sin comparar alternativas', en: 'Immediately hire an external provider without comparing alternatives', fr: 'Engager immédiatement un prestataire externe sans comparer les alternatives' }, value: 35 },
      { id: 'd', text: { es: 'Solicitar al equipo de TI que desarrolle una solución interna sin análisis previo', en: 'Ask the IT team to develop an internal solution without prior analysis', fr: 'Demander à l\'équipe informatique de développer une solution interne sans analyse préalable' }, value: 20 },
    ],
    maxScore: 100,
    aiEvaluated: false,
    order: 5,
    isActive: true,
  },
];
