import jsPDF from 'jspdf';
import type { AnalysisResult, LocalizedString } from '@/types';

type Locale = 'es' | 'en' | 'fr';

// Helper to extract localized text
function t(str: LocalizedString, locale: Locale): string {
  if (locale === 'fr') return str.fr || str.en || str.es || '';
  return str[locale] || str.es || str.en || '';
}

// Labels for all languages
const labels = {
  es: {
    reportTitle: 'Informe de Evaluación de Competencias',
    generatedFor: 'Generado para',
    profile: 'Perfil evaluado',
    date: 'Fecha de análisis',
    confidential: 'Documento confidencial',
    executiveSummary: 'Resumen Ejecutivo',
    overallAssessment: 'Evaluación General',
    indicesTitle: 'Índices de Competencias',
    professional: 'Profesional',
    softSkills: 'Habilidades Blandas',
    readiness: 'Disposición al Cambio',
    strengthsTitle: 'Fortalezas Identificadas',
    opportunitiesTitle: 'Oportunidades de Crecimiento',
    profilesTitle: 'Perfiles Asignados',
    match: 'Coincidencia',
    personalizedMessage: 'Mensaje Personalizado',
    trainingPath: 'Ruta de Capacitación',
    changeStrategies: 'Estrategias de Gestión del Cambio',
    step: 'Paso',
    focusAreas: 'Áreas de enfoque',
    page: 'Página',
    of: 'de',
    generatedBy: 'Generado por skaills',
    excellentRange: 'Excelente',
    goodRange: 'Bueno',
    needsWork: 'Necesita mejorar',
    detailedResults: 'Resultados Detallados',
    recommendationsTitle: 'Recomendaciones',
  },
  en: {
    reportTitle: 'Competency Evaluation Report',
    generatedFor: 'Generated for',
    profile: 'Evaluated profile',
    date: 'Analysis date',
    confidential: 'Confidential document',
    executiveSummary: 'Executive Summary',
    overallAssessment: 'Overall Assessment',
    indicesTitle: 'Competency Indices',
    professional: 'Professional',
    softSkills: 'Soft Skills',
    readiness: 'Readiness',
    strengthsTitle: 'Identified Strengths',
    opportunitiesTitle: 'Growth Opportunities',
    profilesTitle: 'Assigned Profiles',
    match: 'Match',
    personalizedMessage: 'Personalized Message',
    trainingPath: 'Training Path',
    changeStrategies: 'Change Management Strategies',
    step: 'Step',
    focusAreas: 'Focus areas',
    page: 'Page',
    of: 'of',
    generatedBy: 'Generated by skaills',
    excellentRange: 'Excellent',
    goodRange: 'Good',
    needsWork: 'Needs improvement',
    detailedResults: 'Detailed Results',
    recommendationsTitle: 'Recommendations',
  },
  fr: {
    reportTitle: "Rapport d'Évaluation des Compétences",
    generatedFor: 'Généré pour',
    profile: 'Profil évalué',
    date: "Date de l'analyse",
    confidential: 'Document confidentiel',
    executiveSummary: 'Résumé Exécutif',
    overallAssessment: 'Évaluation Générale',
    indicesTitle: 'Indices de Compétences',
    professional: 'Professionnel',
    softSkills: 'Compétences Relationnelles',
    readiness: 'Disposition au Changement',
    strengthsTitle: 'Forces Identifiées',
    opportunitiesTitle: 'Opportunités de Croissance',
    profilesTitle: 'Profils Assignés',
    match: 'Correspondance',
    personalizedMessage: 'Message Personnalisé',
    trainingPath: 'Parcours de Formation',
    changeStrategies: 'Stratégies de Gestion du Changement',
    step: 'Étape',
    focusAreas: 'Domaines ciblés',
    page: 'Page',
    of: 'de',
    generatedBy: 'Généré par skaills',
    excellentRange: 'Excellent',
    goodRange: 'Bon',
    needsWork: 'À améliorer',
    detailedResults: 'Résultats Détaillés',
    recommendationsTitle: 'Recommandations',
  },
};

// Colors
const COLORS = {
  primary: [37, 99, 235] as [number, number, number],       // blue-600
  primaryDark: [29, 78, 216] as [number, number, number],    // blue-700
  primaryLight: [219, 234, 254] as [number, number, number], // blue-100
  secondary: [107, 114, 128] as [number, number, number],    // gray-500
  success: [22, 163, 74] as [number, number, number],        // green-600
  successLight: [220, 252, 231] as [number, number, number], // green-100
  successBg: [240, 253, 244] as [number, number, number],    // green-50
  warning: [234, 179, 8] as [number, number, number],        // yellow-500
  warningLight: [254, 249, 195] as [number, number, number], // yellow-100
  warningBg: [254, 252, 232] as [number, number, number],    // yellow-50
  danger: [220, 38, 38] as [number, number, number],         // red-600
  dangerLight: [254, 226, 226] as [number, number, number],  // red-100
  dangerBg: [254, 242, 242] as [number, number, number],     // red-50
  accent: [147, 51, 234] as [number, number, number],        // purple-600
  accentLight: [243, 232, 255] as [number, number, number],  // purple-100
  dark: [31, 41, 55] as [number, number, number],            // gray-800
  mediumDark: [55, 65, 81] as [number, number, number],      // gray-700
  medium: [75, 85, 99] as [number, number, number],          // gray-600
  light: [243, 244, 246] as [number, number, number],        // gray-100
  lighter: [249, 250, 251] as [number, number, number],      // gray-50
  white: [255, 255, 255] as [number, number, number],
  barBg: [229, 231, 235] as [number, number, number],        // gray-200
  divider: [209, 213, 219] as [number, number, number],      // gray-300
  blueBg: [239, 246, 255] as [number, number, number],       // blue-50
};

function getScoreColor(score: number): [number, number, number] {
  if (score >= 75) return COLORS.success;
  if (score >= 50) return COLORS.warning;
  return COLORS.danger;
}

function getScoreBgColor(score: number): [number, number, number] {
  if (score >= 75) return COLORS.successBg;
  if (score >= 50) return COLORS.warningBg;
  return COLORS.dangerBg;
}

function getScoreLightColor(score: number): [number, number, number] {
  if (score >= 75) return COLORS.successLight;
  if (score >= 50) return COLORS.warningLight;
  return COLORS.dangerLight;
}

export async function generateResultsPdf(
  result: AnalysisResult,
  locale: Locale
): Promise<void> {
  const l = labels[locale] || labels.en;
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth(); // 210
  const pageHeight = pdf.internal.pageSize.getHeight(); // 297
  const margin = 20;
  const contentWidth = pageWidth - margin * 2; // 170
  let y = margin;

  // Parse date
  const analyzedDate = result.analyzedAt?.toDate
    ? result.analyzedAt.toDate()
    : new Date(result.analyzedAt as unknown as string);
  const dateLocaleMap: Record<string, string> = { es: 'es-ES', en: 'en-US', fr: 'fr-FR' };
  const dateStr = analyzedDate.toLocaleDateString(
    dateLocaleMap[locale] || 'en-US',
    { year: 'numeric', month: 'long', day: 'numeric' }
  );

  // ========================================
  // UTILITY FUNCTIONS
  // ========================================
  function addFooter(pageNum: number, totalPages: number) {
    // Footer line
    pdf.setDrawColor(...COLORS.divider);
    pdf.setLineWidth(0.3);
    pdf.line(margin, pageHeight - 18, pageWidth - margin, pageHeight - 18);

    // Page number on right
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.secondary);
    pdf.text(
      `${l.page} ${pageNum} ${l.of} ${totalPages}`,
      pageWidth - margin,
      pageHeight - 12,
      { align: 'right' }
    );

    // "Generated by skaills" on left
    pdf.text(l.generatedBy, margin, pageHeight - 12);
  }

  function addAllFooters() {
    const totalPages = pdf.getNumberOfPages();
    for (let i = 2; i <= totalPages; i++) { // skip cover page
      pdf.setPage(i);
      addFooter(i - 1, totalPages - 1);
    }
  }

  function checkPageBreak(requiredSpace: number): void {
    if (y + requiredSpace > pageHeight - 25) {
      pdf.addPage();
      y = margin;
    }
  }

  function drawSectionTitle(title: string): void {
    checkPageBreak(18);
    // Colored left bar
    pdf.setFillColor(...COLORS.primary);
    pdf.rect(margin, y - 5, 3, 12, 'F');

    pdf.setFontSize(15);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.dark);
    pdf.text(title, margin + 7, y + 2);
    y += 4;

    // Subtle bottom line
    pdf.setDrawColor(...COLORS.barBg);
    pdf.setLineWidth(0.3);
    pdf.line(margin + 7, y, margin + contentWidth, y);
    y += 8;
  }

  function drawSubsectionTitle(title: string): void {
    checkPageBreak(12);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.mediumDark);
    pdf.text(title, margin + 4, y);
    y += 7;
  }

  // ========================================
  // PAGE 1: COVER PAGE
  // ========================================
  // Full-page gradient-like background using layered rects
  // Top section - primary blue
  pdf.setFillColor(...COLORS.primary);
  pdf.rect(0, 0, pageWidth, pageHeight * 0.6, 'F');

  // Bottom section - white
  pdf.setFillColor(...COLORS.white);
  pdf.rect(0, pageHeight * 0.6, pageWidth, pageHeight * 0.4, 'F');

  // Decorative diagonal stripe
  pdf.setFillColor(...COLORS.primaryDark);
  pdf.triangle(0, pageHeight * 0.55, pageWidth, pageHeight * 0.5, pageWidth, pageHeight * 0.6, 'F');
  pdf.setFillColor(...COLORS.white);
  pdf.triangle(0, pageHeight * 0.58, 0, pageHeight * 0.6, pageWidth, pageHeight * 0.6, 'F');

  // skaills logo text
  pdf.setFontSize(36);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.white);
  pdf.text('skaills', margin + 5, 55);

  // Small accent line under logo
  pdf.setDrawColor(255, 255, 255);
  pdf.setLineWidth(1);
  pdf.line(margin + 5, 60, margin + 55, 60);

  // Report title
  pdf.setFontSize(26);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.white);
  const titleLines = pdf.splitTextToSize(l.reportTitle, contentWidth - 10);
  pdf.text(titleLines, margin + 5, 85);

  // Candidate name - large
  const candidateNameY = 85 + titleLines.length * 12 + 15;
  pdf.setFontSize(22);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(219, 234, 254); // blue-100
  pdf.text(result.candidateName, margin + 5, candidateNameY);

  // Profile evaluated
  pdf.setFontSize(13);
  pdf.setTextColor(191, 219, 254); // blue-200
  pdf.text(`${l.profile}: ${result.profileId}`, margin + 5, candidateNameY + 14);

  // Bottom area info
  const bottomInfoY = pageHeight * 0.68;

  // Date
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.medium);
  pdf.text(`${l.date}:`, margin + 5, bottomInfoY);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.dark);
  pdf.text(dateStr, margin + 5, bottomInfoY + 8);

  // Confidential notice
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(...COLORS.secondary);
  pdf.text(l.confidential, margin + 5, bottomInfoY + 22);

  // Footer branding bar
  pdf.setFillColor(...COLORS.primary);
  pdf.rect(0, pageHeight - 12, pageWidth, 12, 'F');
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.white);
  pdf.text('skaills', pageWidth / 2, pageHeight - 4, { align: 'center' });

  // ========================================
  // PAGE 2: EXECUTIVE SUMMARY
  // ========================================
  pdf.addPage();
  y = margin;

  drawSectionTitle(l.executiveSummary);

  // Three score cards side by side
  const cardWidth = (contentWidth - 12) / 3; // 3 cards with 6mm gap each
  const cardHeight = 52;
  const cardY = y;
  const scores = [
    { label: l.professional, value: result.indices.professional },
    { label: l.softSkills, value: result.indices.softSkills },
    { label: l.readiness, value: result.indices.readiness },
  ];

  for (let i = 0; i < 3; i++) {
    const cardX = margin + i * (cardWidth + 6);
    const score = scores[i];
    const scoreColor = getScoreColor(score.value);
    const scoreBg = getScoreBgColor(score.value);
    const scoreLightColor = getScoreLightColor(score.value);

    // Card background
    pdf.setFillColor(...scoreBg);
    pdf.roundedRect(cardX, cardY, cardWidth, cardHeight, 3, 3, 'F');

    // Colored top strip
    pdf.setFillColor(...scoreLightColor);
    pdf.roundedRect(cardX, cardY, cardWidth, 14, 3, 3, 'F');
    // Flatten bottom corners of top strip
    pdf.setFillColor(...scoreLightColor);
    pdf.rect(cardX, cardY + 10, cardWidth, 4, 'F');

    // Category label
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...scoreColor);
    pdf.text(score.label.toUpperCase(), cardX + cardWidth / 2, cardY + 9, { align: 'center' });

    // Score value - big
    pdf.setFontSize(28);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...scoreColor);
    pdf.text(`${Math.round(score.value)}`, cardX + cardWidth / 2, cardY + 33, { align: 'center' });

    // Score label
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...scoreColor);
    const scoreLabel = score.value >= 75
      ? l.excellentRange
      : score.value >= 50
        ? l.goodRange
        : l.needsWork;
    pdf.text(scoreLabel, cardX + cardWidth / 2, cardY + 40, { align: 'center' });

    // Mini progress bar
    const miniBarWidth = cardWidth - 16;
    const miniBarX = cardX + 8;
    const miniBarY = cardY + 44;
    pdf.setFillColor(...COLORS.barBg);
    pdf.roundedRect(miniBarX, miniBarY, miniBarWidth, 3, 1.5, 1.5, 'F');
    const filledMiniBar = (score.value / 100) * miniBarWidth;
    pdf.setFillColor(...scoreColor);
    if (filledMiniBar > 0) {
      pdf.roundedRect(miniBarX, miniBarY, Math.max(filledMiniBar, 3), 3, 1.5, 1.5, 'F');
    }
  }

  y = cardY + cardHeight + 12;

  // Overall assessment text
  drawSubsectionTitle(l.overallAssessment);

  const overallScore = Math.round(
    (result.indices.professional + result.indices.softSkills + result.indices.readiness) / 3
  );
  const message = t(result.recommendations.personalizedMessage, locale);

  // Assessment box
  checkPageBreak(30);
  pdf.setFillColor(...COLORS.blueBg);
  pdf.setDrawColor(...COLORS.primaryLight);
  pdf.setLineWidth(0.5);
  const msgLines = pdf.splitTextToSize(message, contentWidth - 20);
  const msgBoxHeight = msgLines.length * 5 + 12;
  pdf.roundedRect(margin, y - 4, contentWidth, msgBoxHeight, 3, 3, 'FD');

  // Blue left accent bar
  pdf.setFillColor(...COLORS.primary);
  pdf.roundedRect(margin, y - 4, 3, msgBoxHeight, 1.5, 1.5, 'F');

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.dark);
  pdf.text(msgLines, margin + 10, y + 3);
  y += msgBoxHeight + 8;

  // Quick summary - overall score
  checkPageBreak(16);
  pdf.setFillColor(...COLORS.lighter);
  pdf.roundedRect(margin, y - 2, contentWidth, 12, 2, 2, 'F');
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.medium);
  const avgLabel = locale === 'es'
    ? 'Puntuación promedio general'
    : locale === 'fr'
      ? 'Score moyen global'
      : 'Overall average score';
  pdf.text(`${avgLabel}:`, margin + 6, y + 5);

  const avgColor = getScoreColor(overallScore);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...avgColor);
  pdf.text(`${overallScore}%`, margin + contentWidth - 6, y + 5.5, { align: 'right' });
  y += 18;

  // ========================================
  // PAGE 3+: DETAILED RESULTS
  // ========================================
  pdf.addPage();
  y = margin;

  drawSectionTitle(l.detailedResults);

  // --- Competency Indices with full bars ---
  drawSubsectionTitle(l.indicesTitle);

  for (const score of scores) {
    checkPageBreak(18);

    // Label
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.dark);
    pdf.text(score.label, margin + 4, y);

    // Score value on right
    const color = getScoreColor(score.value);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...color);
    pdf.text(`${Math.round(score.value)}%`, margin + contentWidth - 4, y, { align: 'right' });

    y += 4;

    // Full-width progress bar
    const barHeight = 7;
    pdf.setFillColor(...COLORS.barBg);
    pdf.roundedRect(margin + 4, y, contentWidth - 8, barHeight, 3, 3, 'F');
    const filledWidth = (score.value / 100) * (contentWidth - 8);
    pdf.setFillColor(...color);
    if (filledWidth > 0) {
      pdf.roundedRect(margin + 4, y, Math.max(filledWidth, 6), barHeight, 3, 3, 'F');
    }

    y += barHeight + 8;
  }

  y += 5;

  // --- Strengths section ---
  drawSubsectionTitle(l.strengthsTitle);

  const strengthTexts = result.strengths.map((s) => t(s, locale));
  for (const item of strengthTexts) {
    checkPageBreak(12);

    // Green checkmark icon (circle + check simulation)
    pdf.setFillColor(...COLORS.successLight);
    pdf.circle(margin + 7, y - 1.5, 3, 'F');
    pdf.setFillColor(...COLORS.success);
    pdf.circle(margin + 7, y - 1.5, 2, 'F');
    // White checkmark: small lines
    pdf.setDrawColor(...COLORS.white);
    pdf.setLineWidth(0.6);
    pdf.line(margin + 5.5, y - 1.5, margin + 6.7, y - 0.3);
    pdf.line(margin + 6.7, y - 0.3, margin + 8.5, y - 2.7);

    // Text
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.dark);
    const lines = pdf.splitTextToSize(item, contentWidth - 18);
    pdf.text(lines, margin + 14, y);
    y += lines.length * 5 + 4;
  }

  y += 6;

  // --- Growth Opportunities section ---
  drawSubsectionTitle(l.opportunitiesTitle);

  const opportunityTexts = result.growthOpportunities.map((o) => t(o, locale));
  for (const item of opportunityTexts) {
    checkPageBreak(12);

    // Amber arrow icon (circle + arrow simulation)
    pdf.setFillColor(...COLORS.warningLight);
    pdf.circle(margin + 7, y - 1.5, 3, 'F');
    pdf.setFillColor(...COLORS.warning);
    pdf.circle(margin + 7, y - 1.5, 2, 'F');
    // White upward arrow
    pdf.setDrawColor(...COLORS.white);
    pdf.setLineWidth(0.6);
    pdf.line(margin + 7, y - 3, margin + 7, y + 0.2);
    pdf.line(margin + 5.8, y - 1.5, margin + 7, y - 3);
    pdf.line(margin + 8.2, y - 1.5, margin + 7, y - 3);

    // Text
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.dark);
    const lines = pdf.splitTextToSize(item, contentWidth - 18);
    pdf.text(lines, margin + 14, y);
    y += lines.length * 5 + 4;
  }

  y += 5;

  // ========================================
  // ASSIGNED PROFILES SECTION
  // ========================================
  checkPageBreak(30);
  drawSectionTitle(l.profilesTitle);

  const profileEntries = [
    { label: l.professional, profile: result.assignedProfiles.professional, color: COLORS.primary },
    { label: l.softSkills, profile: result.assignedProfiles.softSkills, color: COLORS.accent },
    { label: l.readiness, profile: result.assignedProfiles.readiness, color: COLORS.success },
  ];

  for (const entry of profileEntries) {
    const profileName = t(entry.profile.profileName, locale);
    const explanation = t(entry.profile.explanation, locale);
    const explLines = pdf.splitTextToSize(explanation, contentWidth - 20);
    const cardH = 28 + explLines.length * 4;

    checkPageBreak(cardH + 5);

    // Card background
    pdf.setFillColor(...COLORS.lighter);
    pdf.roundedRect(margin, y - 4, contentWidth, cardH, 3, 3, 'F');

    // Left color bar
    pdf.setFillColor(...entry.color);
    pdf.roundedRect(margin, y - 4, 3, cardH, 1.5, 1.5, 'F');

    // Category badge
    pdf.setFillColor(...entry.color);
    const badgeWidth = pdf.getTextWidth(entry.label.toUpperCase()) + 8;
    pdf.roundedRect(margin + 8, y - 3, badgeWidth > 20 ? badgeWidth : 20, 7, 2, 2, 'F');
    pdf.setFontSize(7);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.white);
    pdf.text(entry.label.toUpperCase(), margin + 10, y + 1.5);
    // Ensure correct badge width
    pdf.setFontSize(7);

    // Profile name
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.dark);
    pdf.text(profileName, margin + 8, y + 12);

    // Match percentage bar
    const matchBarX = margin + contentWidth - 55;
    const matchBarWidth = 40;
    const matchBarY = y + 7;

    // Bar background
    pdf.setFillColor(...COLORS.barBg);
    pdf.roundedRect(matchBarX, matchBarY, matchBarWidth, 5, 2.5, 2.5, 'F');

    // Filled bar
    const matchColor = getScoreColor(entry.profile.matchPercentage);
    const matchFilled = (entry.profile.matchPercentage / 100) * matchBarWidth;
    pdf.setFillColor(...matchColor);
    if (matchFilled > 0) {
      pdf.roundedRect(matchBarX, matchBarY, Math.max(matchFilled, 5), 5, 2.5, 2.5, 'F');
    }

    // Match percentage text
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...matchColor);
    pdf.text(
      `${Math.round(entry.profile.matchPercentage)}%`,
      matchBarX + matchBarWidth + 4,
      matchBarY + 4
    );

    // Explanation
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.medium);
    pdf.text(explLines, margin + 8, y + 18);

    y += cardH + 6;
  }

  y += 3;

  // ========================================
  // RECOMMENDATIONS SECTION
  // ========================================
  checkPageBreak(30);
  drawSectionTitle(l.recommendationsTitle);

  // --- Personalized Message ---
  drawSubsectionTitle(l.personalizedMessage);

  checkPageBreak(20);
  const recMessage = t(result.recommendations.personalizedMessage, locale);
  const recMsgLines = pdf.splitTextToSize(recMessage, contentWidth - 20);
  const recMsgHeight = recMsgLines.length * 5 + 10;

  pdf.setFillColor(...COLORS.blueBg);
  pdf.roundedRect(margin, y - 4, contentWidth, recMsgHeight, 3, 3, 'F');
  pdf.setFillColor(...COLORS.primary);
  pdf.roundedRect(margin, y - 4, 3, recMsgHeight, 1.5, 1.5, 'F');

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(...COLORS.dark);
  pdf.text(recMsgLines, margin + 10, y + 2);
  y += recMsgHeight + 8;

  // --- Training Path as Visual Roadmap ---
  if (result.recommendations.trainingPath.length > 0) {
    checkPageBreak(20);
    drawSubsectionTitle(l.trainingPath);

    const steps = result.recommendations.trainingPath;
    for (let i = 0; i < steps.length; i++) {
      const step = steps[i];
      const resourceName = t(step.resource.name, locale);
      const rationale = t(step.rationale, locale);
      const ratLines = pdf.splitTextToSize(rationale, contentWidth - 30);

      // Calculate focus area text
      let focusText = '';
      if (step.focusAreas && step.focusAreas.length > 0) {
        focusText = step.focusAreas.map((fa) => t(fa, locale)).join(' · ');
      }
      const focusLines = focusText
        ? pdf.splitTextToSize(`${l.focusAreas}: ${focusText}`, contentWidth - 30)
        : [];

      const stepHeight = 12 + ratLines.length * 4 + (focusLines.length > 0 ? focusLines.length * 4 + 4 : 0) + 6;

      checkPageBreak(stepHeight + 8);

      // Timeline vertical line (connecting dots)
      if (i < steps.length - 1) {
        pdf.setDrawColor(...COLORS.primaryLight);
        pdf.setLineWidth(1);
        pdf.line(margin + 8, y + 6, margin + 8, y + stepHeight + 2);
      }

      // Step number circle
      pdf.setFillColor(...COLORS.primary);
      pdf.circle(margin + 8, y + 1, 5, 'F');
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(...COLORS.white);
      pdf.text(`${step.order}`, margin + 8, y + 2.5, { align: 'center' });

      // Step card background
      pdf.setFillColor(...COLORS.lighter);
      pdf.roundedRect(margin + 18, y - 5, contentWidth - 18, stepHeight - 2, 2, 2, 'F');

      // Resource name
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(...COLORS.dark);
      pdf.text(resourceName, margin + 22, y + 2);

      // Rationale
      let stepY = y + 8;
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(...COLORS.medium);
      pdf.text(ratLines, margin + 22, stepY);
      stepY += ratLines.length * 4 + 2;

      // Focus areas as inline badges
      if (focusLines.length > 0) {
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'italic');
        pdf.setTextColor(...COLORS.accent);
        pdf.text(focusLines, margin + 22, stepY);
        stepY += focusLines.length * 4 + 2;
      }

      y += stepHeight + 4;
    }
  }

  y += 5;

  // --- Change Management Strategies ---
  if (result.recommendations.changeManagementStrategies.length > 0) {
    checkPageBreak(20);
    drawSectionTitle(l.changeStrategies);

    const strategies = result.recommendations.changeManagementStrategies.map(
      (s) => t(s, locale)
    );

    for (let i = 0; i < strategies.length; i++) {
      checkPageBreak(12);

      // Numbered circle
      pdf.setFillColor(...COLORS.accentLight);
      pdf.circle(margin + 7, y - 1.2, 3.5, 'F');
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(...COLORS.accent);
      pdf.text(`${i + 1}`, margin + 7, y, { align: 'center' });

      // Strategy text
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(...COLORS.dark);
      const lines = pdf.splitTextToSize(strategies[i], contentWidth - 18);
      pdf.text(lines, margin + 14, y);
      y += lines.length * 5 + 4;
    }
  }

  // ========================================
  // ADD FOOTERS TO ALL PAGES (except cover)
  // ========================================
  addAllFooters();

  // ========================================
  // SAVE
  // ========================================
  const safeName = result.candidateName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  pdf.save(`skaills-report-${safeName}.pdf`);
}
